services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      - API_PORT=3000
      - FRONTEND_PORT=8000
      - APP_PORT=8080
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      api:
        condition: service_started
      frontend:
        condition: service_healthy
  api:
    build: ./api
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/api:latest
    # this is for JWT_SECRET & REFRESH_SECRET, add this in prod
    # env_file: ./api/.env
    volumes:
      - sqlite_db:/data
    environment:
      - PORT=3000
      - DB_CONN=/data/db.sqlite
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
      - REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
    expose:
      - "3000"
    restart: on-failure

  frontend:
    build: ./frontend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/frontend:latest
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000"]
      interval: 5s
      retries: 5
    environment:
      - PORT=8000
    expose:
      - "8000"
    restart: on-failure

volumes:
  sqlite_db:
  caddy_data:
  caddy_config:
