name: Backup DB

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - main
    paths:
      - 'api/db/**'
  workflow_dispatch:
    
jobs:
  backup-db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Copy and backup the .sqlite file
        uses: appleboy/ssh-action@v1
        with:
          host: "${{ secrets.HOST }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            db_path=$(docker volume inspect linking_sqlite_db --format json | jq --raw-output '.[].Mountpoint')
            backup_name="db_backup_$(date +%Y_%m_%d_%H_%M_%S).sqlite"
            [[ -d ~/linking/ ]] || mkdir -p ~/linking
            backup_path="~/linking/$backup_name"
            rm ~/linking/db_backup_*.sqlite || true
            cp $db_path/db.sqlite ~/linking/"$backup_name"
