name: Build and deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ./README.md
      - ./api/tests/*

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner
        run: |
          echo "LOWERCASE_GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push all images
        uses: docker/bake-action@v6
        # env:
        #   JWT_SECRET: ${{ secrets.JWT_SECRET }}
        #   REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
        with:
          files: docker-compose.yml
          push: true
          set: |
            *.platform=linux/amd64
            *.args.GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy the Caddyfile to server
        uses: appleboy/scp-action@master
        with:
          host: "${{ secrets.HOST }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "Caddyfile"
          target: "~/linking/"

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: "${{ secrets.HOST }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/linking/"

      - name: Lowercase repository owner
        run: |
          echo "LOWERCASE_GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Deploy stack via ssh
        uses: appleboy/ssh-action@v1
        env:
          LOWERCASE_GITHUB_REPOSITORY_OWNER: ${{ env.LOWERCASE_GITHUB_REPOSITORY_OWNER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        with:
          host: "${{ secrets.HOST }}"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/linking
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export LOWERCASE_GITHUB_REPOSITORY_OWNER=${{ env.LOWERCASE_GITHUB_REPOSITORY_OWNER }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            docker compose  -f docker-compose.prod.yml pull
            docker compose  -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
